spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # none, update
  h2:
    console.enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

aws:
  sqs:
    endpoint: http://localhost:4566
    queue:
      partial: http://sqs.us-east-2.localhost.localstack.cloud:4566/000000000000/partial-queue
      excess: http://sqs.us-east-2.localhost.localstack.cloud:4566/000000000000/excess-queue
      total: http://sqs.us-east-2.localhost.localstack.cloud:4566/000000000000/total-queue
  region: us-east-2